name: Update index.html

on:
  push:

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install jinja2
        
      - name: Render JSON to HTML
        run: python3 render_json_to_html.py
        
      - name: Run index.html generator
        run: |
          python3 generate_index.py
          touch .nojekyll

      - name: Commit and Push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git diff --cached --quiet || git commit -m "Auto-update index.html [GitHub Actions]"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/watchstep/mock_resume_test.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: main
          folder: . 
